ALTER TABLE "Programa" ADD COLUMN IF NOT EXISTS "secretaria" TEXT NOT NULL DEFAULT 'PA';
ALTER TABLE "Articulo" ADD COLUMN IF NOT EXISTS "secretaria" TEXT NOT NULL DEFAULT 'PA';
ALTER TABLE "Remito" ADD COLUMN IF NOT EXISTS "secretaria" TEXT NOT NULL DEFAULT 'PA';
ALTER TABLE "EntregaProgramada" ADD COLUMN IF NOT EXISTS "secretaria" TEXT NOT NULL DEFAULT 'PA';
ALTER TABLE "Tarea" ADD COLUMN IF NOT EXISTS "secretaria" TEXT NOT NULL DEFAULT 'PA';
